install.packages("dplyr")
library(dplyr)
class(odi)
head(odi)
Aamer<-filter(odi,Player=="Aamer Hanif"|Player=="Sachin R Tendulkar")
dim(Aamer)
subset(odi,Player=="Aamer Hanif")
names(select(odi,Country,Player,Runs))
names(select(odi,-Ground,-ScoreRate))
Sachin<-filter(odi,Player=="Sachin R Tendulkar")
Sachin %>% summarise("Total Runs"=sum(Runs),"Avg Runs"=mean(Runs))
Sachin %>% summarise("Total Runs"=mean(Runs))
class(Sachin)
names(Sachin)
India<-filter(odi,Country=="India")
head(India)
India %>% summarise("Total Runs India"=sum(Runs),"Avg Runs India"=mean(Runs))
CountryName<-odi%>% group_by(Country)%>%summarise(TotalRuns=sum(Runs),AvgRuns=mean(Runs))
==================
BankCampaign <- read.csv("D:/ML/Bank Campaign.csv")
names(BankCampaign)
head(BankCampaign)
Job1<-BankCampaign%>%group_by(Job)%>%summarise("Total"=sum(Response.Rate),"Count"=n())%>%mutate(PerRespnse=Total/Count*100)%>%arrange(-PerRespnse)

Summary<-BankCampaign%>%group_by(Job)%>%summarise("Total"=sum(Response.Rate),"Count"=n())%>%mutate(PerRespnse=Total/Count*100)%>%arrange(-Count)
SummaryAge<-BankCampaign%>%group_by(Age.Group)%>%summarise("Total"=sum(Response.Rate),"Count"=n())%>%mutate(PerRespnse=Total/Count*100)%>%arrange(-PerRespnse)
library(ggplot2)
ggplot(SummaryAge,aes(x=SummaryAge$Age.Group,y=SummaryAge$Count,fill=-SummaryAge$PerRespnse))+geom_bar(stat = "identity")
ggplot(SummaryAge,aes(x=SummaryAge$Age.Group,y=SummaryAge$PerRespnse,fill=SummaryAge$Age.Group))+geom_bar(stat = "identity")+coord_flip()
CountryName<-odi%>% group_by(Country)%>%summarise(TotalRuns=sum(Runs),AvgRuns=mean(Runs))
ggplot(CountryName,aes(x=CountryName$Country,y=CountryName$TotalRuns,fill=CountryName$Country))+geom_bar(stat = "identity")+coord_flip()
ggplot(Job1,aes(x=Job1$Job,y=Job1$Count,fill=-Job1$PerRespnse))+geom_bar(stat="identity")+coord_flip()+labs(x="Job",y="Frequency")
---------------------
  cricket data
head(odi)
countrysummary<-odi%>%group_by(Country)%>%summarise(TotalRuns=sum(!is.na(Runs)),Avg=mean(!is.na(Runs)))
ggplot(countrysummary,aes(x=countrysummary$Country,y=countrysummary$TotalRuns,fill=-countrysummary$Avg))+geom_bar(stat = "identity")+coord_flip()
ggplot(odi,aes(x=1,y=Runs))+geom_boxplot(notch=FALSE, outlier.shape=NA, fill="red", alpha=0.1)+coord_flip()
ggplot(odi,aes(Runs))+geom_histogram(bins = 5)
class(odi)
summaryPlayers<-odi%>%group_by(Player)%>%summarise(TotalRuns=sum(Runs),AvgRuns=mean(Runs))%>%arrange(-TotalRuns)
head(summaryPlayers)
TopPlayers<-head(summaryPlayers,25)
india1<-filter(odi,Country=="India")
View(india1)
indianplayer<-india1%>%group_by(Player)%>%summarise(TotalRuns=sum(Runs),AvgRuns=mean(Runs))%>%arrange(-TotalRuns)
abc<-head(indianplayer,25)
ggplot(abc,aes(x=factor(Player,levels = unique(Player)),y=TotalRuns,fill=-AvgRuns))+geom_bar(stat = "identity")+coord_flip()
str(odi)
odisachin<-filter(odi,Player=="Sachin R Tendulkar")
ggplot(odisachin,aes(x=Runs,y=ScoreRate))+geom_point(colour="Red")+geom_smooth()
dim(TopPlayers)
summaryPlayers<-odi%>%group_by(Player)%>%summarise(TotalRuns=sum(Runs),AvgRuns=mean(Runs))%>%arrange(-TotalRuns)
head(summaryPlayers)
TopPlayers<-head(summaryPlayers,10)
TopPlayers_name<-TopPlayers$Player
TopPlayers_name
TopplayerFilter<-filter(odi,odi$Player%in%TopPlayers_name)
topPlayer_odi<-odi[odi$Player %in%TopPlayers_name,]
ggplot(topPlayer_odi,aes(x=Runs,y=ScoreRate))+geom_point()+geom_smooth()+facet_wrap(~Player)
ggplot(topPlayer_odi,aes(x=Runs,y=ScoreRate))+geom_smooth()+facet_wrap(~Player)
dim(TopplayerFilter)
dim(topPlayer_odi)
View(TopplayerFilter)
sehwag<-filter(odi,Player=="Virender Sehwag")
ggplot(sehwag,aes(x=Runs,y=ScoreRate))+geom_point()+geom_smooth(se=FALSE)
ggplot(sehwag,aes(x=Runs,y=ScoreRate))+geom_point()+geom_smooth()
-----------------------------
YearOdi<-odi%>%group_by(Year)%>%summarise(ToTalRuns=sum(Runs,na.rm=T))%>%arrange(-ToTalRuns)
ggplot(YearOdi,aes(x=Year,y=ToTalRuns))+geom_bar(stat = "identity")

sachin<-filter(odi,odi$Player=="Sachin R Tendulkar")
YearSachin<-sachin%>%group_by(Year)%>%summarise(ToTalRuns=sum(Runs,na.rm=T))%>%arrange(-ToTalRuns)
ggplot(YearSachin,aes(x=Year,y=ToTalRuns))+geom_bar(stat = "identity")
ggplot(YearSachin,aes(x=Year,y=ToTalRuns))+geom_line(stat = "identity")+geom_smooth()

ggplot(YearOdi,aes(x=Year,y=ToTalRuns))+geom_line()+geom_smooth()
YearOdi1<-odi%>%group_by(Year)%>%summarise(ToTalRuns=sum(Runs,na.rm=T))%>%arrange(-Year)
str(odi)
Summary<-BankCampaign%>%group_by(Job)%>%summarise("Total"=sum(Response.Rate),"Count"=n())%>%mutate(PerRespnse=Total/Count*100)%>%arrange(-Count)
Count1<-odi%>%group_by(Year)%>%summarise(count=n())%>%arrange(-Year)
Count1<-odi%>%group_by(Year)%>%summarise(count=n())%>%arrange(-Year)
ggplot(Count1,aes(x=Year,y=count))+geom_bar(stat = "identity")+scale_x_continuous(breaks = scales::pretty_breaks(n=20))
Count1
